### ISSUE TITLE
Implement task managing system and server side backend to manage users accounts.

### ISSUE THREAD

**Issue by Litenoo** [Litenoo/VueCalendar#3]
- [x] - Nice and clear login/register site.
- [X] - Add VueRouter and sessions to access cookies to authenticate users

- [ ] - Redirection to day after clicking day representation in month view

**Task creating view component**
   - -[x] - adding task
   - -[x] - smooth animation while creating task
   - -[x] - title
   - -[ ] - content only after open
   - -[x] - duration in hrs (can use display multiplier)
   - -[x] - color Picker or color palette [Used browser built-in one]
   - Other features for task system :
   - -[ ] - moving task thru other grids by dragging it to left or right
   - -[ ] - deleting task 
   - -[ ] - Changing task status (done, pending, not started,  etc.)
   - **Database task connection** 
   - -[x] - saving task
   - -[ ] - deleting task
   - -[ ] - status of task
   
   
**bugs to repair : **
- - [ ] - Line on top of week view (Maybe also on others) is a little to short
- - [ ] - After clicking gear icon to go to settings and going back then the icon is positioned different as before
- - [ ] - If there is two tasks colliding in duration display, make one snap to right and second to the left and think if 
-- [ ] - When loading year view there are couple of errors occur.

- -[ ] - Issue switching months doesn't work on year view
